spring.application.name=shareholder-management

spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.4.113)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.4.114)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ibuat)))

spring.datasource.username=share998
spring.datasource.password=PAss123#

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

