spring.application.name=shareholder-management
spring.datasource.url=${SBMS_DB_URL:jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.4.113)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.4.114)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ibuat)))}
spring.datasource.username=${SBMS_DB_USERNAME:share998}
spring.datasource.password=${SBMS_DB_PASSWORD:PAss123#}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true